# Generated by Django 5.2.9 on 2026-01-13 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='游戏名称')),
                ('description', models.TextField(blank=True, verbose_name='游戏描述')),
                ('novel_file', models.FileField(upload_to='novels/', verbose_name='小说文件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('world_setting', models.JSONField(default=dict, verbose_name='世界观设定')),
                ('characters', models.JSONField(default=dict, verbose_name='角色数据')),
                ('story_tree', models.JSONField(default=dict, verbose_name='剧情树')),
                ('attributes', models.JSONField(default=dict, verbose_name='属性系统')),
                ('items', models.JSONField(default=dict, verbose_name='物品系统')),
                ('exploration', models.JSONField(default=dict, verbose_name='探索系统')),
                ('analysis_progress', models.IntegerField(default=0, verbose_name='分析进度')),
                ('analysis_status', models.CharField(default='pending', max_length=50, verbose_name='分析状态')),
            ],
            options={
                'verbose_name': '游戏项目',
                'verbose_name_plural': '游戏项目',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_models', to='game.gameproject')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('content', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='game.gameproject')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_models', to='game.gameproject')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('content', models.JSONField(default=dict)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='game.chapter')),
            ],
            options={
                'verbose_name': '场景',
                'verbose_name_plural': '场景',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('chunk_content', models.TextField()),
                ('analysis_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_cache', to='game.gameproject')),
            ],
            options={
                'verbose_name': '分析缓存',
                'verbose_name_plural': '分析缓存',
                'unique_together': {('project', 'chunk_index')},
            },
        ),
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(default=0, verbose_name='存档槽位')),
                ('save_name', models.CharField(max_length=100, verbose_name='存档名称')),
                ('current_chapter', models.CharField(max_length=100)),
                ('current_scene', models.CharField(max_length=100)),
                ('current_node', models.CharField(max_length=100)),
                ('player_attributes', models.JSONField(default=dict)),
                ('player_inventory', models.JSONField(default=list)),
                ('player_flags', models.JSONField(default=list)),
                ('relationship_data', models.JSONField(default=dict)),
                ('exploration_data', models.JSONField(default=dict)),
                ('play_time', models.IntegerField(default=0, verbose_name='游戏时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='game.gameproject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '游戏存档',
                'verbose_name_plural': '游戏存档',
                'unique_together': {('project', 'user', 'slot')},
            },
        ),
    ]
